[supabase]
url = "https://yahnwjusqykwgpehzrge.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaG53anVzcXlrd2dwZWh6cmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1ODE0MjAsImV4cCI6MjA0OTE1NzQyMH0.G2P_YGxqID7tBvDOjz4Sa3q7vsMRIw595tLdd24GbMs"

